# This file was generated by GoReleaser. DO NOT EDIT.
cask "apiki" do
  artifact "apiki", target: "#{HOMEBREW_PREFIX}/share/apiki/apiki"
  artifact "init.bash", target: "#{HOMEBREW_PREFIX}/share/apiki/init.bash"
  artifact "init.zsh", target: "#{HOMEBREW_PREFIX}/share/apiki/init.zsh"
  artifact "init.fish", target: "#{HOMEBREW_PREFIX}/share/apiki/init.fish"

  name "apiki"
  desc "TUI environment variable manager"
  homepage "https://loderunner.github.io/apiki"
  version "0.3.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apiki"

  on_macos do
    on_intel do
      url "https://github.com/loderunner/apiki/releases/download/v#{version}/apiki_#{version}_darwin_amd64.tar.gz"
      sha256 "6a0bc3eb7f2664c5a933297a90382f86c224dd863595c533cfefd4c74e6641ae"
    end
    on_arm do
      url "https://github.com/loderunner/apiki/releases/download/v#{version}/apiki_#{version}_darwin_arm64.tar.gz"
      sha256 "d45c6ed700510d9b11d5ff6e6fd61ff664af09eef61b209ebf55f6917364afaa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/loderunner/apiki/releases/download/v#{version}/apiki_#{version}_linux_amd64.tar.gz"
      sha256 "a519411b7a6edeb514da01802615e7a4a15a8ad740a512fc6f16708900daa71b"
    end
    on_arm do
      url "https://github.com/loderunner/apiki/releases/download/v#{version}/apiki_#{version}_linux_arm64.tar.gz"
      sha256 "a13f208b49af33ef579202d3e6127c4f3615baf95d49646c2cfce4f0ec0890ba"
    end
  end

  caveats do
    "apiki requires shell integration to work. Add to your shell config:"
    ""
    "For bash (~/.bashrc):"
    "  export APIKI_DIR="#{HOMEBREW_PREFIX}/share/apiki""
    "  [ -s "$APIKI_DIR/init.bash" ] && . "$APIKI_DIR/init.bash""
    ""
    "For zsh (~/.zshrc):"
    "  export APIKI_DIR="#{HOMEBREW_PREFIX}/share/apiki""
    "  [ -s "$APIKI_DIR/init.zsh" ] && . "$APIKI_DIR/init.zsh""
    ""
    "For fish (~/.config/fish/config.fish):"
    "  set -gx APIKI_DIR "#{HOMEBREW_PREFIX}/share/apiki""
    "  source "$APIKI_DIR/init.fish""
    ""
    "Then restart your shell or source the config file."
  end

  # No zap stanza required
end
