# This file was generated by GoReleaser. DO NOT EDIT.
cask "apiki" do
  artifact "apiki", target: "#{HOMEBREW_PREFIX}/share/apiki/apiki"
  artifact "init.bash", target: "#{HOMEBREW_PREFIX}/share/apiki/init.bash"
  artifact "init.zsh", target: "#{HOMEBREW_PREFIX}/share/apiki/init.zsh"
  artifact "init.fish", target: "#{HOMEBREW_PREFIX}/share/apiki/init.fish"

  name "apiki"
  desc "TUI environment variable manager"
  homepage "https://loderunner.github.io/apiki"
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apiki"

  on_macos do
    on_intel do
      url "https://github.com/loderunner/apiki/releases/download/v#{version}/apiki_#{version}_darwin_amd64.tar.gz"
      sha256 "7967951c18de4d0338b7f9da64edd8d5a4a1ef29f6754ddd604088ae827575d8"
    end
    on_arm do
      url "https://github.com/loderunner/apiki/releases/download/v#{version}/apiki_#{version}_darwin_arm64.tar.gz"
      sha256 "fb88cb6d03738428ddce0cb53de4ce06a11e064389614bfae402fdff66339298"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/loderunner/apiki/releases/download/v#{version}/apiki_#{version}_linux_amd64.tar.gz"
      sha256 "a8f00761a27b6e300de471e6fd9519be4cc38ba4958852b907ed16cc91af1c39"
    end
    on_arm do
      url "https://github.com/loderunner/apiki/releases/download/v#{version}/apiki_#{version}_linux_arm64.tar.gz"
      sha256 "6183b57016f5045919ad77efb9cfddf31c0df3f3ece352ba536727f20b016c89"
    end
  end

  caveats do
    "apiki requires shell integration to work. Add to your shell config:"
    ""
    "For bash (~/.bashrc):"
    "  export APIKI_DIR="#{HOMEBREW_PREFIX}/share/apiki""
    "  [ -s "$APIKI_DIR/init.bash" ] && . "$APIKI_DIR/init.bash""
    ""
    "For zsh (~/.zshrc):"
    "  export APIKI_DIR="#{HOMEBREW_PREFIX}/share/apiki""
    "  [ -s "$APIKI_DIR/init.zsh" ] && . "$APIKI_DIR/init.zsh""
    ""
    "For fish (~/.config/fish/config.fish):"
    "  set -gx APIKI_DIR "#{HOMEBREW_PREFIX}/share/apiki""
    "  source "$APIKI_DIR/init.fish""
    ""
    "Then restart your shell or source the config file."
  end

  # No zap stanza required
end
