# This file was generated by GoReleaser. DO NOT EDIT.
cask "apiki" do
  artifact "apiki", target: "#{HOMEBREW_PREFIX}/share/apiki/apiki"
  artifact "init.bash", target: "#{HOMEBREW_PREFIX}/share/apiki/init.bash"
  artifact "init.zsh", target: "#{HOMEBREW_PREFIX}/share/apiki/init.zsh"
  artifact "init.fish", target: "#{HOMEBREW_PREFIX}/share/apiki/init.fish"

  name "apiki"
  desc "TUI environment variable manager"
  homepage "https://loderunner.github.io/apiki"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apiki"

  on_macos do
    on_intel do
      url "https://github.com/loderunner/apiki/releases/download/v#{version}/apiki_#{version}_darwin_amd64.tar.gz"
      sha256 "fd93d381fb97df27e8b9d149de6f90a9eef79c82749f309c39fe3ae367b903b0"
    end
    on_arm do
      url "https://github.com/loderunner/apiki/releases/download/v#{version}/apiki_#{version}_darwin_arm64.tar.gz"
      sha256 "06fce044f1ccb4f3b52c6d56e8b44c7bc3544dd6b50859c8a186e04cb3965146"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/loderunner/apiki/releases/download/v#{version}/apiki_#{version}_linux_amd64.tar.gz"
      sha256 "e2116e0a3788cec6d5730c6c2c83911e266cccf0e1b7f23fbb5e60f2f770cfbe"
    end
    on_arm do
      url "https://github.com/loderunner/apiki/releases/download/v#{version}/apiki_#{version}_linux_arm64.tar.gz"
      sha256 "b211155cb4e1b2ce42b667bd4c1e311234b84160ba2ac67d1ed4bb8bd31fb446"
    end
  end

  caveats do
    "apiki requires shell integration to work. Add to your shell config:"
    ""
    "For bash (~/.bashrc):"
    "  export APIKI_DIR="#{HOMEBREW_PREFIX}/share/apiki""
    "  [ -s "$APIKI_DIR/init.bash" ] && . "$APIKI_DIR/init.bash""
    ""
    "For zsh (~/.zshrc):"
    "  export APIKI_DIR="#{HOMEBREW_PREFIX}/share/apiki""
    "  [ -s "$APIKI_DIR/init.zsh" ] && . "$APIKI_DIR/init.zsh""
    ""
    "For fish (~/.config/fish/config.fish):"
    "  set -gx APIKI_DIR "#{HOMEBREW_PREFIX}/share/apiki""
    "  source "$APIKI_DIR/init.fish""
    ""
    "Then restart your shell or source the config file."
  end

  # No zap stanza required
end
